"""Import AuraDB migration dump into Railway Neo4j.

Reads JSON files from a data/migrations/auradb_export_YYYYMMDD/ directory
and loads them into a fresh Railway Neo4j instance using the same MERGE
keys as the original loaders.

Usage:
    python import_to_railway.py [--export-dir=data/migrations/auradb_export_20260322] [--dry-run]

--dry-run reads the export files and prints counts without writing to Railway.

Requires in .env:
    RAILWAY_NEO4J_URI      e.g. neo4j+s://xyz.railway.app:7687
    RAILWAY_NEO4J_USER     e.g. neo4j
    RAILWAY_NEO4J_PASSWORD e.g. <generated by Railway>
"""

from __future__ import annotations

import json
import logging
import os
import sys
from pathlib import Path
from typing import Any

from dotenv import load_dotenv
from neo4j import Driver

load_dotenv()
logging.basicConfig(level=logging.INFO, format="%(levelname)s  %(message)s")
logger = logging.getLogger(__name__)

_BATCH_SIZE = 2_000


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _load_json(export_dir: Path, filename: str) -> list[dict[str, Any]]:
    """Read a JSON array from *export_dir/filename*.

    Args:
        export_dir: Directory containing the migration dump.
        filename: JSON file to load.

    Returns:
        Parsed list of dicts.

    Raises:
        FileNotFoundError: If the file does not exist.
    """
    path = export_dir / filename
    with open(path, encoding="utf-8") as fh:
        data = json.load(fh)
    logger.info("Loaded %10d  %s", len(data), filename)
    return data


def _run_batched(
    driver: Driver,
    query: str,
    rows: list[dict[str, Any]],
    label: str,
) -> None:
    """Execute *query* in batches of _BATCH_SIZE rows.

    Args:
        driver: Open Neo4j driver.
        query: Cypher UNWIND query expecting ``$rows`` parameter.
        rows: Full dataset to submit.
        label: Human-readable label for log output.
    """
    total = len(rows)
    for start in range(0, total, _BATCH_SIZE):
        batch = rows[start : start + _BATCH_SIZE]
        with driver.session() as session:
            session.run(query, rows=batch)
    logger.info("Imported %10d  %s", total, label)


# ---------------------------------------------------------------------------
# Schema constraints
# ---------------------------------------------------------------------------


def create_constraints(driver: Driver) -> None:
    """Create uniqueness constraints on Railway Neo4j Community Edition.

    Only ``IS UNIQUE`` (single-property) constraints are used — Neo4j
    Community Edition does not support Node Key (multi-property unique)
    constraints.  CFBD coaches are identified by ``(first_name, last_name)``
    which cannot have a Community Edition uniqueness constraint; MERGE on
    that pair still works correctly via a full-scan, just without an index.
    McIllece coaches are keyed by ``coach_code`` which gets an IS UNIQUE
    constraint for fast idempotent MERGE.

    Note: ``Team.school`` is intentionally NOT constrained — 35 non-FBS
    school names appear under multiple CFBD team IDs (different division
    entries).  AuraDB never had a school uniqueness constraint either.
    Any leftover ``Team.school`` constraint from a prior script version
    is detected and dropped automatically.

    Args:
        driver: Open Neo4j driver pointed at Railway.
    """
    # ── Drop any leftover constraints from previous script versions ────────
    # Earlier versions created a Team.school IS UNIQUE constraint, which
    # conflicts with duplicate non-FBS schools in the export data.
    with driver.session() as session:
        rows = session.run(
            "SHOW CONSTRAINTS YIELD name, labelsOrTypes, properties, type"
        ).data()
    bad = [
        r["name"] for r in rows
        if r.get("labelsOrTypes") == ["Team"]
        and r.get("properties") == ["school"]
        and r.get("type") == "UNIQUENESS"
    ]
    for name in bad:
        with driver.session() as session:
            session.run(f"DROP CONSTRAINT `{name}`")
        logger.info("Dropped leftover Team.school constraint: %s", name)

    # ── Create the correct Community Edition constraints ───────────────────
    constraints = [
        "CREATE CONSTRAINT IF NOT EXISTS FOR (n:Team)       REQUIRE n.id         IS UNIQUE",
        "CREATE CONSTRAINT IF NOT EXISTS FOR (n:Player)     REQUIRE n.id          IS UNIQUE",
        "CREATE CONSTRAINT IF NOT EXISTS FOR (n:Conference) REQUIRE n.name        IS UNIQUE",
        "CREATE CONSTRAINT IF NOT EXISTS FOR (n:Coach)      REQUIRE n.coach_code  IS UNIQUE",
    ]
    with driver.session() as session:
        for cypher in constraints:
            session.run(cypher)
    logger.info("Constraints created (or already exist)")


# ---------------------------------------------------------------------------
# Node importers
# ---------------------------------------------------------------------------


def import_teams(driver: Driver, export_dir: Path) -> int:
    """MERGE Team nodes from nodes_Team.json.

    Args:
        driver: Open Neo4j driver.
        export_dir: Directory containing the migration dump.

    Returns:
        Number of records submitted.
    """
    rows = _load_json(export_dir, "nodes_Team.json")
    _run_batched(
        driver,
        """
        UNWIND $rows AS row
        MERGE (t:Team {id: row.id})
        SET t.school       = row.school,
            t.conference   = row.conference,
            t.abbreviation = row.abbreviation
        """,
        rows,
        "Team nodes",
    )
    return len(rows)


def import_conferences(driver: Driver, export_dir: Path) -> int:
    """MERGE Conference nodes from nodes_Conference.json.

    Args:
        driver: Open Neo4j driver.
        export_dir: Directory containing the migration dump.

    Returns:
        Number of records submitted.
    """
    rows = _load_json(export_dir, "nodes_Conference.json")
    _run_batched(
        driver,
        "UNWIND $rows AS row MERGE (c:Conference {name: row.name})",
        rows,
        "Conference nodes",
    )
    return len(rows)


def import_coaches(driver: Driver, export_dir: Path) -> int:
    """MERGE Coach nodes from nodes_Coach.json.

    Handles both CFBD coaches (first_name/last_name) and McIllece coaches
    (coach_code).  Each coach type is submitted separately so the correct
    MERGE key is used.

    Args:
        driver: Open Neo4j driver.
        export_dir: Directory containing the migration dump.

    Returns:
        Number of records submitted.
    """
    rows = _load_json(export_dir, "nodes_Coach.json")

    # CFBD coaches are keyed by (first_name, last_name)
    cfbd = [r for r in rows if r.get("first_name") and not r.get("coach_code")]
    # McIllece coaches are keyed by coach_code
    mcillece = [r for r in rows if r.get("coach_code")]

    if cfbd:
        _run_batched(
            driver,
            """
            UNWIND $rows AS row
            MERGE (c:Coach {first_name: row.first_name, last_name: row.last_name})
            """,
            cfbd,
            "Coach nodes (cfbd)",
        )

    if mcillece:
        _run_batched(
            driver,
            """
            UNWIND $rows AS row
            MERGE (c:Coach {coach_code: row.coach_code})
            SET c.name       = row.name,
                c.coach_code = row.coach_code
            """,
            mcillece,
            "Coach nodes (mcillece)",
        )

    return len(rows)


def import_players(driver: Driver, export_dir: Path) -> int:
    """MERGE Player nodes from nodes_Player.json.

    Args:
        driver: Open Neo4j driver.
        export_dir: Directory containing the migration dump.

    Returns:
        Number of records submitted.
    """
    rows = _load_json(export_dir, "nodes_Player.json")
    _run_batched(
        driver,
        """
        UNWIND $rows AS row
        MERGE (p:Player {id: row.id})
        SET p.name     = row.name,
            p.position = row.position,
            p.hometown = row.hometown
        """,
        rows,
        "Player nodes",
    )
    return len(rows)


# ---------------------------------------------------------------------------
# Relationship importers
# ---------------------------------------------------------------------------


def import_played_for(driver: Driver, export_dir: Path) -> int:
    """MERGE PLAYED_FOR relationships from rels_PLAYED_FOR.json.

    MERGE key: (Player.id, Team.school, year).

    Args:
        driver: Open Neo4j driver.
        export_dir: Directory containing the migration dump.

    Returns:
        Number of records submitted.
    """
    rows = _load_json(export_dir, "rels_PLAYED_FOR.json")
    _run_batched(
        driver,
        """
        UNWIND $rows AS row
        MATCH (p:Player {id: row.player_id})
        MATCH (t:Team   {school: row.team_school})
        MERGE (p)-[r:PLAYED_FOR {year: row.year}]->(t)
        SET r.jersey = row.jersey
        """,
        rows,
        "PLAYED_FOR rels",
    )
    return len(rows)


def import_coached_at_cfbd(driver: Driver, export_dir: Path) -> int:
    """MERGE COACHED_AT (source=None/CFBD) from rels_COACHED_AT_cfbd.json.

    MERGE key: (Coach.first_name, Coach.last_name, Team.school, title,
                start_year) — matches original load_coaches() logic.

    Args:
        driver: Open Neo4j driver.
        export_dir: Directory containing the migration dump.

    Returns:
        Number of records submitted.
    """
    rows = _load_json(export_dir, "rels_COACHED_AT_cfbd.json")
    _run_batched(
        driver,
        """
        UNWIND $rows AS row
        MATCH (c:Coach {first_name: row.first_name, last_name: row.last_name})
        MATCH (t:Team  {school: row.team_school})
        MERGE (c)-[r:COACHED_AT {title: row.title, start_year: row.start_year}]->(t)
        SET r.end_year = row.end_year
        """,
        rows,
        "COACHED_AT (cfbd) rels",
    )
    return len(rows)


def import_coached_at_mcillece(driver: Driver, export_dir: Path) -> int:
    """MERGE COACHED_AT (source='mcillece') from rels_COACHED_AT_mcillece.json.

    MERGE key: (coach_code, year, team_code) — matches load_staff() logic.

    Args:
        driver: Open Neo4j driver.
        export_dir: Directory containing the migration dump.

    Returns:
        Number of records submitted.
    """
    rows = _load_json(export_dir, "rels_COACHED_AT_mcillece.json")
    _run_batched(
        driver,
        """
        UNWIND $rows AS row
        MATCH (c:Coach {coach_code: row.coach_code})
        MATCH (t:Team  {school: row.team_school})
        MERGE (c)-[r:COACHED_AT {
            coach_code: row.coach_code,
            year:       row.year,
            team_code:  row.team_code
        }]->(t)
        SET r.roles  = row.roles,
            r.source = 'mcillece'
        """,
        rows,
        "COACHED_AT (mcillece) rels",
    )
    return len(rows)


def import_coached_at_mcillece_roles(driver: Driver, export_dir: Path) -> int:
    """MERGE COACHED_AT (source='mcillece_roles') from rels_COACHED_AT_mcillece_roles.json.

    MERGE key: (coach_code, year, team_code, role_abbr) — matches
    load_coached_at_roles() logic.

    Args:
        driver: Open Neo4j driver.
        export_dir: Directory containing the migration dump.

    Returns:
        Number of records submitted.
    """
    rows = _load_json(export_dir, "rels_COACHED_AT_mcillece_roles.json")

    # Flatten rel_props dict into the row so UNWIND can access individual fields
    flat = [
        {
            "coach_code": r["coach_code"],
            "team_school": r["team_school"],
            **r["rel_props"],
        }
        for r in rows
    ]

    _run_batched(
        driver,
        """
        UNWIND $rows AS row
        MATCH (c:Coach {coach_code: row.coach_code})
        MATCH (t:Team  {school: row.team_school})
        MERGE (c)-[r:COACHED_AT {
            coach_code: row.coach_code,
            year:       row.year,
            team_code:  row.team_code,
            role_abbr:  row.role_abbr
        }]->(t)
        SET r.role           = row.role,
            r.role_tier      = row.role_tier,
            r.is_coordinator = row.is_coordinator,
            r.coach_name     = row.coach_name,
            r.source         = 'mcillece_roles'
        """,
        flat,
        "COACHED_AT (mcillece_roles) rels",
    )
    return len(rows)


def import_played(driver: Driver, export_dir: Path) -> int:
    """MERGE PLAYED relationships from rels_PLAYED.json.

    MERGE key: game_id on the relationship.

    Args:
        driver: Open Neo4j driver.
        export_dir: Directory containing the migration dump.

    Returns:
        Number of records submitted.
    """
    rows = _load_json(export_dir, "rels_PLAYED.json")

    flat = [
        {
            "home_school": r["home_school"],
            "away_school": r["away_school"],
            **r["rel_props"],
        }
        for r in rows
    ]

    _run_batched(
        driver,
        """
        UNWIND $rows AS row
        MATCH (home:Team {school: row.home_school})
        MATCH (away:Team {school: row.away_school})
        MERGE (home)-[r:PLAYED {game_id: row.game_id}]->(away)
        SET r.home_score = row.home_score,
            r.away_score = row.away_score,
            r.season     = row.season,
            r.week       = row.week
        """,
        flat,
        "PLAYED rels",
    )
    return len(rows)


def import_in_conference(driver: Driver, export_dir: Path) -> int:
    """MERGE IN_CONFERENCE relationships from rels_IN_CONFERENCE.json.

    Args:
        driver: Open Neo4j driver.
        export_dir: Directory containing the migration dump.

    Returns:
        Number of records submitted.
    """
    rows = _load_json(export_dir, "rels_IN_CONFERENCE.json")
    _run_batched(
        driver,
        """
        UNWIND $rows AS row
        MATCH (t:Team       {school: row.team_school})
        MATCH (c:Conference {name:   row.conference_name})
        MERGE (t)-[:IN_CONFERENCE]->(c)
        """,
        rows,
        "IN_CONFERENCE rels",
    )
    return len(rows)


def import_mentored(driver: Driver, export_dir: Path) -> int:
    """MERGE MENTORED relationships from rels_MENTORED.json.

    Coaches may be identified by first/last name (CFBD) or coach_code
    (McIllece).  Pairs are split by available identity and loaded with
    the appropriate MATCH key.

    Args:
        driver: Open Neo4j driver.
        export_dir: Directory containing the migration dump.

    Returns:
        Number of records submitted.
    """
    rows = _load_json(export_dir, "rels_MENTORED.json")

    # Coaches with coach_code on both ends → match by code
    by_code = [
        r for r in rows
        if r.get("mentor_code") and r.get("mentee_code")
    ]
    # All others → match by first/last name
    by_name = [
        r for r in rows
        if not (r.get("mentor_code") and r.get("mentee_code"))
    ]

    if by_name:
        _run_batched(
            driver,
            """
            UNWIND $rows AS row
            MATCH (mentor:Coach {first_name: row.mentor_first, last_name: row.mentor_last})
            MATCH (mentee:Coach {first_name: row.mentee_first, last_name: row.mentee_last})
            MERGE (mentor)-[:MENTORED]->(mentee)
            """,
            by_name,
            "MENTORED rels (name-keyed)",
        )

    if by_code:
        _run_batched(
            driver,
            """
            UNWIND $rows AS row
            MATCH (mentor:Coach {coach_code: row.mentor_code})
            MATCH (mentee:Coach {coach_code: row.mentee_code})
            MERGE (mentor)-[:MENTORED]->(mentee)
            """,
            by_code,
            "MENTORED rels (code-keyed)",
        )

    return len(rows)


# ---------------------------------------------------------------------------
# Orchestrator
# ---------------------------------------------------------------------------


def import_all(driver: Driver, export_dir: Path) -> dict[str, int]:
    """Import all nodes and relationships from the export directory.

    Load order mirrors the original pipeline to satisfy FK-like MATCH
    requirements (Teams must exist before Conferences links them, etc.).

    Args:
        driver: Open Neo4j driver pointing at Railway.
        export_dir: Directory produced by export_auradb.py.

    Returns:
        ``{label: count}`` for every import step.
    """
    create_constraints(driver)

    counts: dict[str, int] = {}

    # Nodes first — order matters (Teams → Conferences → Coaches → Players)
    counts["nodes_Team"]       = import_teams(driver, export_dir)
    counts["nodes_Conference"] = import_conferences(driver, export_dir)
    counts["nodes_Coach"]      = import_coaches(driver, export_dir)
    counts["nodes_Player"]     = import_players(driver, export_dir)

    # Relationships — after all nodes exist
    counts["rels_PLAYED_FOR"]                = import_played_for(driver, export_dir)
    counts["rels_COACHED_AT_cfbd"]           = import_coached_at_cfbd(driver, export_dir)
    counts["rels_COACHED_AT_mcillece"]       = import_coached_at_mcillece(driver, export_dir)
    counts["rels_COACHED_AT_mcillece_roles"] = import_coached_at_mcillece_roles(driver, export_dir)
    counts["rels_PLAYED"]                    = import_played(driver, export_dir)
    counts["rels_IN_CONFERENCE"]             = import_in_conference(driver, export_dir)
    counts["rels_MENTORED"]                  = import_mentored(driver, export_dir)

    return counts


# ---------------------------------------------------------------------------
# Entry-point
# ---------------------------------------------------------------------------


def _latest_export_dir() -> Path:
    """Return the most recently created export directory under data/migrations/.

    Returns:
        Path to the export directory.

    Raises:
        FileNotFoundError: If no export directories exist.
    """
    base = Path("data/migrations")
    dirs = sorted(base.glob("auradb_export_*"), reverse=True)
    if not dirs:
        raise FileNotFoundError(
            f"No auradb_export_* directories found under {base}. "
            "Run export_auradb.py first."
        )
    return dirs[0]


def main(*, export_dir: Path | None = None, dry_run: bool = False) -> None:
    """Run the full Railway import.

    Args:
        export_dir: Override the export directory (defaults to latest).
        dry_run: If True, load files and print counts without writing.
    """
    resolved_dir = export_dir or _latest_export_dir()
    logger.info("Import source: %s", resolved_dir)

    if dry_run:
        logger.info("[dry-run] Reading export files — no Railway writes")
        for filename in sorted(resolved_dir.glob("*.json")):
            with open(filename, encoding="utf-8") as fh:
                data = json.load(fh)
            print(f"  {filename.name:<50} {len(data):>10,}")
        return

    uri = os.environ.get("RAILWAY_NEO4J_URI", "")
    user = os.environ.get("RAILWAY_NEO4J_USER", "")
    password = os.environ.get("RAILWAY_NEO4J_PASSWORD", "")
    if not all([uri, user, password]):
        raise EnvironmentError(
            "RAILWAY_NEO4J_URI, RAILWAY_NEO4J_USER, and RAILWAY_NEO4J_PASSWORD "
            "must be set in .env"
        )

    from loader.neo4j_loader import get_driver

    driver = get_driver(uri, user, password)
    try:
        counts = import_all(driver, resolved_dir)
    finally:
        driver.close()

    total_nodes = sum(v for k, v in counts.items() if k.startswith("nodes_"))
    total_rels = sum(v for k, v in counts.items() if k.startswith("rels_"))

    print("\n=== Railway Import Summary ===")
    for key in sorted(counts):
        print(f"  {key:<45} {counts[key]:>10,}")
    print(f"\n  Total nodes         {total_nodes:>10,}")
    print(f"  Total relationships {total_rels:>10,}")
    print("\nImport complete. Run verify_railway.py to confirm counts.")


if __name__ == "__main__":
    args = sys.argv[1:]
    dir_arg = next((a for a in args if a.startswith("--export-dir=")), None)
    resolved = Path(dir_arg.split("=", 1)[1]) if dir_arg else None
    main(export_dir=resolved, dry_run="--dry-run" in args)
