"""Orchestrates the full GraphRAG pipeline: classify → extract → traverse → generate."""

import logging
import os

from google import genai
from google.genai import types
from neo4j import Driver

from graphrag.classifier import classify_intent
from graphrag.entity_extractor import extract_entities, resolve_coach_entity
from graphrag.graph_traversal import (
    get_coach_tree,
    get_coaches_in_conferences,
    get_coaching_tree,
    shortest_path_between_coaches,
)

logger = logging.getLogger(__name__)

_ANSWER_SYSTEM = """You are a college football analyst. You will be given:
1. A user question
2. Structured data retrieved from a knowledge graph

Use the graph data to answer the question accurately and concisely.
If the data is insufficient, say so clearly."""


def _format_provenance(result: dict) -> str:
    """Format an F1 provenance string for a single coaching tree result.

    Args:
        result: Dict from :func:`get_coaching_tree` with keys ``name``,
            ``coach_code``, ``depth``, ``path_coaches``.

    Returns:
        Human-readable provenance string.
    """
    path = " → ".join(result.get("path_coaches") or [])
    depth = result.get("depth", "?")
    return f"Included because: coaching lineage depth {depth} ({path})"


def answer_question(
    question: str,
    driver: Driver,
    client: genai.Client | None = None,
) -> str:
    """Answer a natural language question using GraphRAG.

    Pipeline:
    1. Classify intent via classifier.py (TREE_QUERY | PERFORMANCE_COMPARE | etc.).
    2. Extract entities from the question via Gemini.
    3. Resolve coach entities to CFBD + McIllece node IDs.
    4. Run targeted Cypher traversals based on intent and entity types.
    5. Format results with F1 provenance strings.
    6. Pass graph context to Gemini for final answer generation.

    Args:
        question: Natural language question about college football.
        driver: Open Neo4j driver connected to the loaded graph.
        client: Optional ``genai.Client`` for answer generation.
            If omitted a new client is created using ``GEMINI_API_KEY`` from env.

    Returns:
        A natural language answer string generated by Gemini.
    """
    if client is None:
        client = genai.Client(api_key=os.environ["GEMINI_API_KEY"])

    # 1. Classify intent
    classification = classify_intent(question, client=client)
    intent = classification["intent"]
    logger.info("Classified intent: %s (confidence=%.2f)", intent, classification["confidence"])

    # 2. Entity extraction uses the same client
    entities = extract_entities(question, client=client)
    logger.info("Extracted entities: %s", entities)

    graph_context: list[str] = []

    # 3. Route to the appropriate traversal based on intent
    if intent == "TREE_QUERY" and entities["coaches"]:
        coach_name = entities["coaches"][0]
        resolved = resolve_coach_entity(coach_name, driver)
        mc_code = resolved["mc_coach_code"]

        if mc_code is not None:
            # Use McIllece coaching tree (MENTORED edges)
            tree_results = get_coaching_tree(
                coach_code=mc_code,
                role_filter="HC",
                max_depth=4,
                driver=driver,
            )
            provenance_lines = [_format_provenance(r) for r in tree_results]
            names = [r["name"] for r in tree_results]
            graph_context.append(
                f"Coaching tree (HC mentees) for {coach_name}:\n"
                + "\n".join(f"  {n}  |  {p}" for n, p in zip(names, provenance_lines))
            )
        else:
            # Fall back to CFBD-based traversal
            tree = get_coach_tree(driver, coach_name)
            if tree:
                graph_context.append(f"Coaching tree for {coach_name}:\n{tree}")

    elif intent in ("PERFORMANCE_COMPARE", "PIPELINE_QUERY", "CHANGE_IMPACT"):
        # General coach / conference traversals
        for coach_name in entities["coaches"]:
            tree = get_coach_tree(driver, coach_name)
            if tree:
                graph_context.append(f"Coaching data for {coach_name}:\n{tree}")

        if entities["teams"]:
            coaches = get_coaches_in_conferences(driver, entities["teams"])
            if coaches:
                graph_context.append(f"Coaches across {entities['teams']}:\n{coaches}")

    elif intent == "SIMILARITY" and len(entities["coaches"]) == 2:
        path = shortest_path_between_coaches(
            driver, entities["coaches"][0], entities["coaches"][1]
        )
        if path:
            graph_context.append(
                f"Path between {entities['coaches'][0]} and {entities['coaches'][1]}:\n{path}"
            )

    else:
        # Fallback: try all traversals
        for coach_name in entities["coaches"]:
            tree = get_coach_tree(driver, coach_name)
            if tree:
                graph_context.append(f"Coaching tree for {coach_name}:\n{tree}")

        if len(entities["teams"]) >= 2:
            coaches = get_coaches_in_conferences(driver, entities["teams"])
            if coaches:
                graph_context.append(f"Coaches across {entities['teams']}:\n{coaches}")

        if len(entities["coaches"]) == 2:
            path = shortest_path_between_coaches(
                driver, entities["coaches"][0], entities["coaches"][1]
            )
            if path:
                graph_context.append(
                    f"Path between {entities['coaches'][0]} and {entities['coaches'][1]}:\n{path}"
                )

    context_str = (
        "\n\n".join(graph_context) if graph_context else "No relevant graph data found."
    )

    response = client.models.generate_content(
        model="gemini-2.0-flash",
        contents=f"Question: {question}\n\nGraph data:\n{context_str}",
        config=types.GenerateContentConfig(system_instruction=_ANSWER_SYSTEM),
    )
    return response.text
