"""Orchestrates the full GraphRAG pipeline: extract → traverse → generate."""

import logging
import os

import google.generativeai as genai
from neo4j import Driver

from graphrag.entity_extractor import extract_entities
from graphrag.graph_traversal import (
    get_coach_tree,
    get_coaches_in_conferences,
    shortest_path_between_coaches,
)

logger = logging.getLogger(__name__)

_ANSWER_SYSTEM = """You are a college football analyst. You will be given:
1. A user question
2. Structured data retrieved from a knowledge graph

Use the graph data to answer the question accurately and concisely.
If the data is insufficient, say so clearly."""


def answer_question(
    question: str,
    driver: Driver,
    model: genai.GenerativeModel | None = None,
) -> str:
    """Answer a natural language question using GraphRAG.

    Pipeline:
    1. Extract entities from the question via Gemini (entity extractor owns its model).
    2. Run targeted Cypher traversals based on entity types found.
    3. Pass the graph context to Gemini for answer generation.

    Args:
        question: Natural language question about college football.
        driver: Open Neo4j driver connected to the loaded graph.
        model: Optional ``genai.GenerativeModel`` for answer generation.
            If omitted a new model is created using ``GEMINI_API_KEY`` from env.

    Returns:
        A natural language answer string generated by Gemini.
    """
    if model is None:
        genai.configure(api_key=os.environ["GEMINI_API_KEY"])
        model = genai.GenerativeModel(
            model_name="gemini-2.0-flash",
            system_instruction=_ANSWER_SYSTEM,
        )

    # Entity extraction uses its own model (different system instruction)
    entities = extract_entities(question)
    logger.info("Extracted entities: %s", entities)

    graph_context: list[str] = []

    for coach_name in entities["coaches"]:
        tree = get_coach_tree(driver, coach_name)
        if tree:
            graph_context.append(f"Coaching tree for {coach_name}:\n{tree}")

    if len(entities["teams"]) >= 2:
        coaches = get_coaches_in_conferences(driver, entities["teams"])
        if coaches:
            graph_context.append(f"Coaches across {entities['teams']}:\n{coaches}")

    if len(entities["coaches"]) == 2:
        path = shortest_path_between_coaches(
            driver, entities["coaches"][0], entities["coaches"][1]
        )
        if path:
            graph_context.append(
                f"Path between {entities['coaches'][0]} and {entities['coaches'][1]}:\n{path}"
            )

    context_str = "\n\n".join(graph_context) if graph_context else "No relevant graph data found."

    response = model.generate_content(
        f"Question: {question}\n\nGraph data:\n{context_str}"
    )
    return response.text
